// flags.js
// Mapping of ISO 3166-1 numeric codes (as strings) to an object containing the country name and flag icon URL from flagcdn.com.
export const flagIcons = {
    "004": { name: "Afghanistan", url: "https://flagcdn.com/af.svg" },
    "008": { name: "Albania", url: "https://flagcdn.com/al.svg" },
    "012": { name: "Algeria", url: "https://flagcdn.com/dz.svg" },
    "016": { name: "American Samoa", url: "https://flagcdn.com/as.svg" },
    "020": { name: "Andorra", url: "https://flagcdn.com/ad.svg" },
    "024": { name: "Angola", url: "https://flagcdn.com/ao.svg" },
    "028": { name: "Antigua and Barbuda", url: "https://flagcdn.com/ag.svg" },
    "031": { name: "Azerbaijan", url: "https://flagcdn.com/az.svg" },
    "032": { name: "Argentina", url: "https://flagcdn.com/ar.svg" },
    "036": { name: "Australia", url: "https://flagcdn.com/au.svg" },
    "040": { name: "Austria", url: "https://flagcdn.com/at.svg" },
    "044": { name: "Bahamas", url: "https://flagcdn.com/bs.svg" },
    "048": { name: "Bahrain", url: "https://flagcdn.com/bh.svg" },
    "050": { name: "Bangladesh", url: "https://flagcdn.com/bd.svg" },
    "052": { name: "Barbados", url: "https://flagcdn.com/bb.svg" },
    "056": { name: "Belgium", url: "https://flagcdn.com/be.svg" },
    "060": { name: "Bermuda", url: "https://flagcdn.com/bm.svg" },
    "064": { name: "Bhutan", url: "https://flagcdn.com/bt.svg" },
    "068": { name: "Bolivia (Plurinational State of)", url: "https://flagcdn.com/bo.svg" },
    "070": { name: "Bosnia and Herzegovina", url: "https://flagcdn.com/ba.svg" },
    "072": { name: "Botswana", url: "https://flagcdn.com/bw.svg" },
    "074": { name: "Bouvet Island", url: "https://flagcdn.com/bv.svg" },
    "076": { name: "Brazil", url: "https://flagcdn.com/br.svg" },
    "084": { name: "Belize", url: "https://flagcdn.com/bz.svg" },
    "086": { name: "British Indian Ocean Territory", url: "https://flagcdn.com/io.svg" },
    "090": { name: "Solomon Islands", url: "https://flagcdn.com/sb.svg" },
    "092": { name: "British Antarctic Territory", url: "https://flagcdn.com/aq.svg" },
    "096": { name: "Brunei Darussalam", url: "https://flagcdn.com/bn.svg" },
    "100": { name: "Bulgaria", url: "https://flagcdn.com/bg.svg" },
    "104": { name: "Myanmar", url: "https://flagcdn.com/mm.svg" },
    "108": { name: "Burundi", url: "https://flagcdn.com/bi.svg" },
    "112": { name: "Belarus", url: "https://flagcdn.com/by.svg" },
    "116": { name: "Cambodia", url: "https://flagcdn.com/kh.svg" },
    "120": { name: "Cameroon", url: "https://flagcdn.com/cm.svg" },
    "124": { name: "Canada", url: "https://flagcdn.com/ca.svg" },
    "132": { name: "Cabo Verde", url: "https://flagcdn.com/cv.svg" },
    "136": { name: "Cayman Islands", url: "https://flagcdn.com/ky.svg" },
    "140": { name: "Central African Republic", url: "https://flagcdn.com/cf.svg" },
    "144": { name: "Sri Lanka", url: "https://flagcdn.com/lk.svg" },
    "148": { name: "Chad", url: "https://flagcdn.com/td.svg" },
    "152": { name: "Chile", url: "https://flagcdn.com/cl.svg" },
    "156": { name: "China", url: "https://flagcdn.com/cn.svg" },
    "158": { name: "Taiwan, Province of China", url: "https://flagcdn.com/tw.svg" },
    "162": { name: "Christmas Island", url: "https://flagcdn.com/cx.svg" },
    "166": { name: "Cocos (Keeling) Islands", url: "https://flagcdn.com/cc.svg" },
    "170": { name: "Colombia", url: "https://flagcdn.com/co.svg" },
    "174": { name: "Comoros", url: "https://flagcdn.com/km.svg" },
    "175": { name: "Mayotte", url: "https://flagcdn.com/yt.svg" },
    "178": { name: "Congo", url: "https://flagcdn.com/cg.svg" },
    "180": { name: "Congo (Democratic Republic of the)", url: "https://flagcdn.com/cd.svg" },
    "184": { name: "Cook Islands", url: "https://flagcdn.com/ck.svg" },
    "188": { name: "Costa Rica", url: "https://flagcdn.com/cr.svg" },
    "191": { name: "Croatia", url: "https://flagcdn.com/hr.svg" },
    "192": { name: "Cuba", url: "https://flagcdn.com/cu.svg" },
    "196": { name: "Cyprus", url: "https://flagcdn.com/cy.svg" },
    "203": { name: "Czechia", url: "https://flagcdn.com/cz.svg" },
    "204": { name: "Benin", url: "https://flagcdn.com/bj.svg" },
    "208": { name: "Denmark", url: "https://flagcdn.com/dk.svg" },
    "212": { name: "Dominica", url: "https://flagcdn.com/dm.svg" },
    "214": { name: "Dominican Republic", url: "https://flagcdn.com/do.svg" },
    "218": { name: "Ecuador", url: "https://flagcdn.com/ec.svg" },
    "222": { name: "El Salvador", url: "https://flagcdn.com/sv.svg" },
    "226": { name: "Equatorial Guinea", url: "https://flagcdn.com/gq.svg" },
    "231": { name: "Ethiopia", url: "https://flagcdn.com/et.svg" },
    "232": { name: "Eritrea", url: "https://flagcdn.com/er.svg" },
    "233": { name: "Estonia", url: "https://flagcdn.com/ee.svg" },
    "234": { name: "Faroe Islands", url: "https://flagcdn.com/fo.svg" },
    "238": { name: "Falkland Islands (Malvinas)", url: "https://flagcdn.com/fk.svg" },
    "242": { name: "Fiji", url: "https://flagcdn.com/fj.svg" },
    "246": { name: "Finland", url: "https://flagcdn.com/fi.svg" },
    "250": { name: "France", url: "https://flagcdn.com/fr.svg" },
    "254": { name: "French Guiana", url: "https://flagcdn.com/gf.svg" },
    "258": { name: "French Polynesia", url: "https://flagcdn.com/pf.svg" },
    "260": { name: "French Southern Territories", url: "https://flagcdn.com/tf.svg" },
    "262": { name: "Djibouti", url: "https://flagcdn.com/dj.svg" },
    "266": { name: "Gabon", url: "https://flagcdn.com/ga.svg" },
    "270": { name: "Gambia", url: "https://flagcdn.com/gm.svg" },
    "268": { name: "Georgia", url: "https://flagcdn.com/ge.svg" },
    "276": { name: "Germany", url: "https://flagcdn.com/de.svg" },
    "288": { name: "Ghana", url: "https://flagcdn.com/gh.svg" },
    "292": { name: "Gibraltar", url: "https://flagcdn.com/gi.svg" },
    "296": { name: "Kiribati", url: "https://flagcdn.com/ki.svg" },
    "300": { name: "Greece", url: "https://flagcdn.com/gr.svg" },
    "304": { name: "Greenland", url: "https://flagcdn.com/gl.svg" },
    "308": { name: "Grenada", url: "https://flagcdn.com/gd.svg" },
    "312": { name: "Guadeloupe", url: "https://flagcdn.com/gp.svg" },
    "316": { name: "Guam", url: "https://flagcdn.com/gu.svg" },
    "320": { name: "Guatemala", url: "https://flagcdn.com/gt.svg" },
    "324": { name: "Guinea", url: "https://flagcdn.com/gn.svg" },
    "624": { name: "Guinea-Bissau", url: "https://flagcdn.com/gw.svg" },
    "328": { name: "Guyana", url: "https://flagcdn.com/gy.svg" },
    "332": { name: "Haiti", url: "https://flagcdn.com/ht.svg" },
    "334": { name: "Heard Island and McDonald Islands", url: "https://flagcdn.com/hm.svg" },
    "336": { name: "Holy See", url: "https://flagcdn.com/va.svg" },
    "340": { name: "Honduras", url: "https://flagcdn.com/hn.svg" },
    "344": { name: "Hong Kong", url: "https://flagcdn.com/hk.svg" },
    "348": { name: "Hungary", url: "https://flagcdn.com/hu.svg" },
    "352": { name: "Iceland", url: "https://flagcdn.com/is.svg" },
    "356": { name: "India", url: "https://flagcdn.com/in.svg" },
    "360": { name: "Indonesia", url: "https://flagcdn.com/id.svg" },
    "364": { name: "Iran (Islamic Republic of)", url: "https://flagcdn.com/ir.svg" },
    "368": { name: "Iraq", url: "https://flagcdn.com/iq.svg" },
    "372": { name: "Ireland", url: "https://flagcdn.com/ie.svg" },
    "376": { name: "Israel", url: "https://flagcdn.com/il.svg" },
    "380": { name: "Italy", url: "https://flagcdn.com/it.svg" },
    "388": { name: "Jamaica", url: "https://flagcdn.com/jm.svg" },
    "392": { name: "Japan", url: "https://flagcdn.com/jp.svg" },
    "832": { name: "Jersey", url: "https://flagcdn.com/je.svg" },
    "400": { name: "Jordan", url: "https://flagcdn.com/jo.svg" },
    "398": { name: "Kazakhstan", url: "https://flagcdn.com/kz.svg" },
    "404": { name: "Kenya", url: "https://flagcdn.com/ke.svg" },
    "408": { name: "Korea (Democratic People's Republic of)", url: "https://flagcdn.com/kp.svg" },
    "410": { name: "Korea (the Republic of)", url: "https://flagcdn.com/kr.svg" },
    "414": { name: "Kuwait", url: "https://flagcdn.com/kw.svg" },
    "417": { name: "Kyrgyzstan", url: "https://flagcdn.com/kg.svg" },
    "418": { name: "Lao People's Democratic Republic", url: "https://flagcdn.com/la.svg" },
    "428": { name: "Latvia", url: "https://flagcdn.com/lv.svg" },
    "422": { name: "Lebanon", url: "https://flagcdn.com/lb.svg" },
    "426": { name: "Lesotho", url: "https://flagcdn.com/ls.svg" },
    "430": { name: "Liberia", url: "https://flagcdn.com/lr.svg" },
    "434": { name: "Libya", url: "https://flagcdn.com/ly.svg" },
    "438": { name: "Liechtenstein", url: "https://flagcdn.com/li.svg" },
    "440": { name: "Lithuania", url: "https://flagcdn.com/lt.svg" },
    "442": { name: "Luxembourg", url: "https://flagcdn.com/lu.svg" },
    "446": { name: "Macao", url: "https://flagcdn.com/mo.svg" },
    "450": { name: "Madagascar", url: "https://flagcdn.com/mg.svg" },
    "454": { name: "Malawi", url: "https://flagcdn.com/mw.svg" },
    "458": { name: "Malaysia", url: "https://flagcdn.com/my.svg" },
    "462": { name: "Maldives", url: "https://flagcdn.com/mv.svg" },
    "466": { name: "Mali", url: "https://flagcdn.com/ml.svg" },
    "470": { name: "Malta", url: "https://flagcdn.com/mt.svg" },
    "584": { name: "Marshall Islands", url: "https://flagcdn.com/mh.svg" },
    "474": { name: "Martinique", url: "https://flagcdn.com/mq.svg" },
    "478": { name: "Mauritania", url: "https://flagcdn.com/mr.svg" },
    "480": { name: "Mauritius", url: "https://flagcdn.com/mu.svg" },
    "484": { name: "Mexico", url: "https://flagcdn.com/mx.svg" },
    "583": { name: "Micronesia (Federated States of)", url: "https://flagcdn.com/fm.svg" },
    "498": { name: "Moldova (the Republic of)", url: "https://flagcdn.com/md.svg" },
    "492": { name: "Monaco", url: "https://flagcdn.com/mc.svg" },
    "496": { name: "Mongolia", url: "https://flagcdn.com/mn.svg" },
    "499": { name: "Montenegro", url: "https://flagcdn.com/me.svg" },
    "500": { name: "Montserrat", url: "https://flagcdn.com/ms.svg" },
    "504": { name: "Morocco", url: "https://flagcdn.com/ma.svg" },
    "508": { name: "Mozambique", url: "https://flagcdn.com/mz.svg" },
    "516": { name: "Namibia", url: "https://flagcdn.com/na.svg" },
    "520": { name: "Nauru", url: "https://flagcdn.com/nr.svg" },
    "524": { name: "Nepal", url: "https://flagcdn.com/np.svg" },
    "528": { name: "Netherlands", url: "https://flagcdn.com/nl.svg" },
    "540": { name: "New Caledonia", url: "https://flagcdn.com/nc.svg" },
    "554": { name: "New Zealand", url: "https://flagcdn.com/nz.svg" },
    "558": { name: "Nicaragua", url: "https://flagcdn.com/ni.svg" },
    "562": { name: "Niger", url: "https://flagcdn.com/ne.svg" },
    "566": { name: "Nigeria", url: "https://flagcdn.com/ng.svg" },
    "570": { name: "Niue", url: "https://flagcdn.com/nu.svg" },
    "574": { name: "Norfolk Island", url: "https://flagcdn.com/nf.svg" },
    "578": { name: "Norway", url: "https://flagcdn.com/no.svg" },
    "512": { name: "Oman", url: "https://flagcdn.com/om.svg" },
    "586": { name: "Pakistan", url: "https://flagcdn.com/pk.svg" },
    "585": { name: "Palau", url: "https://flagcdn.com/pw.svg" },
    "275": { name: "Palestine, State of", url: "https://flagcdn.com/ps.svg" },
    "591": { name: "Panama", url: "https://flagcdn.com/pa.svg" },
    "598": { name: "Papua New Guinea", url: "https://flagcdn.com/pg.svg" },
    "600": { name: "Paraguay", url: "https://flagcdn.com/py.svg" },
    "604": { name: "Peru", url: "https://flagcdn.com/pe.svg" },
    "608": { name: "Philippines", url: "https://flagcdn.com/ph.svg" },
    "612": { name: "Pitcairn", url: "https://flagcdn.com/pn.svg" },
    "616": { name: "Poland", url: "https://flagcdn.com/pl.svg" },
    "620": { name: "Portugal", url: "https://flagcdn.com/pt.svg" },
    "630": { name: "Puerto Rico", url: "https://flagcdn.com/pr.svg" },
    "634": { name: "Qatar", url: "https://flagcdn.com/qa.svg" },
    "807": { name: "North Macedonia", url: "https://flagcdn.com/mk.svg" },
    "642": { name: "Romania", url: "https://flagcdn.com/ro.svg" },
    "643": { name: "Russian Federation", url: "https://flagcdn.com/ru.svg" },
    "646": { name: "Rwanda", url: "https://flagcdn.com/rw.svg" },
    "652": { name: "Saint Barthélemy", url: "https://flagcdn.com/bl.svg" },
    "654": { name: "Saint Helena, Ascension and Tristan da Cunha", url: "https://flagcdn.com/sh.svg" },
    "659": { name: "Saint Kitts and Nevis", url: "https://flagcdn.com/kn.svg" },
    "662": { name: "Saint Lucia", url: "https://flagcdn.com/lc.svg" },
    "663": { name: "Saint Martin (French part)", url: "https://flagcdn.com/mf.svg" },
    "666": { name: "Saint Pierre and Miquelon", url: "https://flagcdn.com/pm.svg" },
    "670": { name: "Saint Vincent and the Grenadines", url: "https://flagcdn.com/vc.svg" },
    "882": { name: "Samoa", url: "https://flagcdn.com/ws.svg" },
    "674": { name: "San Marino", url: "https://flagcdn.com/sm.svg" },
    "678": { name: "Sao Tome and Principe", url: "https://flagcdn.com/st.svg" },
    "682": { name: "Saudi Arabia", url: "https://flagcdn.com/sa.svg" },
    "686": { name: "Senegal", url: "https://flagcdn.com/sn.svg" },
    "688": { name: "Serbia", url: "https://flagcdn.com/rs.svg" },
    "690": { name: "Seychelles", url: "https://flagcdn.com/sc.svg" },
    "694": { name: "Sierra Leone", url: "https://flagcdn.com/sl.svg" },
    "702": { name: "Singapore", url: "https://flagcdn.com/sg.svg" },
    "534": { name: "Sint Maarten (Dutch part)", url: "https://flagcdn.com/sx.svg" },
    "703": { name: "Slovakia", url: "https://flagcdn.com/sk.svg" },
    "705": { name: "Slovenia", url: "https://flagcdn.com/si.svg" },
    "706": { name: "Somalia", url: "https://flagcdn.com/so.svg" },
    "710": { name: "South Africa", url: "https://flagcdn.com/za.svg" },
    "239": { name: "South Georgia and the South Sandwich Islands", url: "https://flagcdn.com/gs.svg" },
    "728": { name: "South Sudan", url: "https://flagcdn.com/ss.svg" },
    "724": { name: "Spain", url: "https://flagcdn.com/es.svg" },
    "729": { name: "Sudan", url: "https://flagcdn.com/sd.svg" },
    "740": { name: "Suriname", url: "https://flagcdn.com/sr.svg" },
    "744": { name: "Svalbard and Jan Mayen", url: "https://flagcdn.com/sj.svg" },
    "752": { name: "Sweden", url: "https://flagcdn.com/se.svg" },
    "756": { name: "Switzerland", url: "https://flagcdn.com/ch.svg" },
    "760": { name: "Syrian Arab Republic", url: "https://flagcdn.com/sy.svg" },
    "762": { name: "Tajikistan", url: "https://flagcdn.com/tj.svg" },
    "764": { name: "Thailand", url: "https://flagcdn.com/th.svg" },
    "626": { name: "Timor-Leste", url: "https://flagcdn.com/tl.svg" },
    "768": { name: "Togo", url: "https://flagcdn.com/tg.svg" },
    "772": { name: "Tokelau", url: "https://flagcdn.com/tk.svg" },
    "776": { name: "Tonga", url: "https://flagcdn.com/to.svg" },
    "780": { name: "Trinidad and Tobago", url: "https://flagcdn.com/tt.svg" },
    "788": { name: "Tunisia", url: "https://flagcdn.com/tn.svg" },
    "792": { name: "Turkey", url: "https://flagcdn.com/tr.svg" },
    "795": { name: "Turkmenistan", url: "https://flagcdn.com/tm.svg" },
    "796": { name: "Turks and Caicos Islands", url: "https://flagcdn.com/tc.svg" },
    "798": { name: "Tuvalu", url: "https://flagcdn.com/tv.svg" },
    "800": { name: "Uganda", url: "https://flagcdn.com/ug.svg" },
    "804": { name: "Ukraine", url: "https://flagcdn.com/ua.svg" },
    "784": { name: "United Arab Emirates", url: "https://flagcdn.com/ae.svg" },
    "826": { name: "United Kingdom", url: "https://flagcdn.com/gb.svg" },
    "840": { name: "United States of America", url: "https://flagcdn.com/us.svg" },
    "858": { name: "Uruguay", url: "https://flagcdn.com/uy.svg" },
    "860": { name: "Uzbekistan", url: "https://flagcdn.com/uz.svg" },
    "548": { name: "Vanuatu", url: "https://flagcdn.com/vu.svg" },
    "862": { name: "Venezuela (Bolivarian Republic of)", url: "https://flagcdn.com/ve.svg" },
    "704": { name: "Viet Nam", url: "https://flagcdn.com/vn.svg" },
    "850": { name: "Virgin Islands (U.S.)", url: "https://flagcdn.com/vi.svg" },
    "876": { name: "Wallis and Futuna", url: "https://flagcdn.com/wf.svg" },
    "732": { name: "Western Sahara", url: "https://flagcdn.com/eh.svg" },
    "887": { name: "Yemen", url: "https://flagcdn.com/ye.svg" },
    "894": { name: "Zambia", url: "https://flagcdn.com/zm.svg" },
    "716": { name: "Zimbabwe", url: "https://flagcdn.com/zw.svg" }
  };
  